// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDquGzuA0mZOOwiCxgcbaHi8IXD5OoATaw',
    appId: '1:892204666982:web:bb5179a1b753c5d361dda7',
    messagingSenderId: '892204666982',
    projectId: 'spotify-flutter-app-11',
    authDomain: 'spotify-flutter-app-11.firebaseapp.com',
    storageBucket: 'spotify-flutter-app-11.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIlqN2m9Fpj3DLy2Tz-qzfXEVBezMKIjY',
    appId: '1:892204666982:android:62a6b812939da78561dda7',
    messagingSenderId: '892204666982',
    projectId: 'spotify-flutter-app-11',
    storageBucket: 'spotify-flutter-app-11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEH-FpAbrgcPXeHuMgapbMeVzGz_59a9o',
    appId: '1:892204666982:ios:8a7c35ceb7c9490261dda7',
    messagingSenderId: '892204666982',
    projectId: 'spotify-flutter-app-11',
    storageBucket: 'spotify-flutter-app-11.firebasestorage.app',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEH-FpAbrgcPXeHuMgapbMeVzGz_59a9o',
    appId: '1:892204666982:ios:8a7c35ceb7c9490261dda7',
    messagingSenderId: '892204666982',
    projectId: 'spotify-flutter-app-11',
    storageBucket: 'spotify-flutter-app-11.firebasestorage.app',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDquGzuA0mZOOwiCxgcbaHi8IXD5OoATaw',
    appId: '1:892204666982:web:67374ba94240198361dda7',
    messagingSenderId: '892204666982',
    projectId: 'spotify-flutter-app-11',
    authDomain: 'spotify-flutter-app-11.firebaseapp.com',
    storageBucket: 'spotify-flutter-app-11.firebasestorage.app',
  );
}
